const MENU = [
  // Tiffins
  { id: 1, category: "Tiffins", item: "Idli", price: 30, wait: 5 },
  { id: 2, category: "Tiffins", item: "Rava Idli", price: 35, wait: 7 },
  { id: 3, category: "Tiffins", item: "Sambar Idli", price: 30, wait: 7 },
  { id: 4, category: "Tiffins", item: "Vada", price: 30, wait: 6 },
  { id: 5, category: "Tiffins", item: "Sambar Vada", price: 30, wait: 8 },
  { id: 6, category: "Tiffins", item: "Poori", price: 30, wait: 10 },
  { id: 7, category: "Tiffins", item: "Mysore Bonda", price: 30, wait: 8 },
  { id: 8, category: "Tiffins", item: "Plain Dosa", price: 30, wait: 8 },
  { id: 9, category: "Tiffins", item: "Masala Dosa", price: 35, wait: 10 },
  { id: 10, category: "Tiffins", item: "Onion Dosa", price: 35, wait: 10 },
  { id: 11, category: "Tiffins", item: "Karam Dosa", price: 35, wait: 10 },
  { id: 12, category: "Tiffins", item: "Paneer Dosa", price: 50, wait: 12 },
  { id: 13, category: "Tiffins", item: "Butter Dosa", price: 50, wait: 10 },
  { id: 14, category: "Tiffins", item: "Ghee Dosa", price: 50, wait: 10 },
  { id: 15, category: "Tiffins", item: "Upma Pesarattu", price: 40, wait: 12 },
  { id: 16, category: "Tiffins", item: "Onion Pesarattu", price: 40, wait: 12 },
  { id: 17, category: "Tiffins", item: "Upma Onion Pesarattu", price: 45, wait: 14 },
  { id: 18, category: "Tiffins", item: "Set Dosa", price: 50, wait: 10 },
  // Lunch
  { id: 19, category: "Lunch", item: "Chapathi", price: 35, wait: 10 },
  { id: 20, category: "Lunch", item: "Meals", price: 65, wait: 15 },
  { id: 21, category: "Lunch", item: "Veg Dum Biryani", price: 65, wait: 20 },
  { id: 22, category: "Lunch", item: "Jeera Rice", price: 50, wait: 12 },
  { id: 23, category: "Lunch", item: "Spl Jeera Rice", price: 80, wait: 15 },
  { id: 24, category: "Lunch", item: "Spl Veg Pulao", price: 80, wait: 15 },
  { id: 25, category: "Lunch", item: "Spl Paneer Pulao", price: 80, wait: 18 },
  { id: 26, category: "Lunch", item: "Spl Sweet Corn Pulao", price: 80, wait: 18 },
  { id: 27, category: "Lunch", item: "Spl Mutter Pulao", price: 80, wait: 18 },
  // Snacks
  { id: 28, category: "Snacks", item: "Punugulu", price: 30, wait: 10 },
  { id: 29, category: "Snacks", item: "Mirchi Bajji", price: 30, wait: 10 },
  { id: 30, category: "Snacks", item: "Onion Mirchi Bajji", price: 30, wait: 10 },
  { id: 31, category: "Snacks", item: "Cut Mirchi", price: 30, wait: 8 },
  { id: 32, category: "Snacks", item: "Veg/Onion/Palak Pakodi", price: 30, wait: 10 },
  { id: 33, category: "Snacks", item: "Veg Cutlet", price: 30, wait: 12 },
  { id: 34, category: "Snacks", item: "Aloo Pakoda", price: 30, wait: 10 },
  { id: 35, category: "Snacks", item: "Bread Bajji", price: 30, wait: 10 },
  { id: 36, category: "Snacks", item: "Crispy Corn", price: 30, wait: 12 },
  // Chinese
  { id: 37, category: "Chinese", item: "Veg Fried Rice", price: 50, wait: 15 },
  { id: 38, category: "Chinese", item: "Paneer Fried Rice", price: 60, wait: 18 },
  { id: 39, category: "Chinese", item: "Mushroom Fried Rice", price: 60, wait: 18 },
  { id: 40, category: "Chinese", item: "Sweet Corn Fried Rice", price: 60, wait: 18 },
  { id: 41, category: "Chinese", item: "Schezwan Fried Rice", price: 60, wait: 18 },
  { id: 42, category: "Chinese", item: "Chilli Garlic Rice", price: 60, wait: 18 },
  { id: 43, category: "Chinese", item: "Veg Noodles", price: 50, wait: 15 },
  { id: 44, category: "Chinese", item: "Manchurian Noodles", price: 60, wait: 18 },
  { id: 45, category: "Chinese", item: "Paneer Noodles", price: 60, wait: 18 },
  { id: 46, category: "Chinese", item: "Sweet Corn Noodles", price: 60, wait: 18 },
  { id: 47, category: "Chinese", item: "Schezwan Noodles", price: 60, wait: 18 },
  { id: 48, category: "Chinese", item: "Chilli Garlic Noodles", price: 60, wait: 18 },
  // Continental
  { id: 49, category: "Continental", item: "Chocolate Milkshake", price: 80, wait: 8 },
  { id: 50, category: "Continental", item: "Strawberry Milkshake", price: 80, wait: 8 },
  { id: 51, category: "Continental", item: "Blueberry Milkshake", price: 80, wait: 8 },
  { id: 52, category: "Continental", item: "Oreo Milkshake", price: 80, wait: 8 },
  { id: 53, category: "Continental", item: "Triple Chocolate Thick Shake", price: 110, wait: 10 },
  { id: 54, category: "Continental", item: "Oreo Thick Shake", price: 100, wait: 10 },
  { id: 55, category: "Continental", item: "Kit Kat Thick Shake", price: 100, wait: 10 },
  { id: 56, category: "Continental", item: "Vanilla Frappe", price: 100, wait: 10 },
  { id: 57, category: "Continental", item: "Chocolate Strawberry Frappe", price: 120, wait: 10 },
  { id: 58, category: "Continental", item: "Virgin Mojito", price: 70, wait: 5 },
  { id: 59, category: "Continental", item: "Blue Heaven Mojito", price: 70, wait: 5 },
  { id: 60, category: "Continental", item: "Watermelon Mojito", price: 70, wait: 5 },
  { id: 61, category: "Continental", item: "French Fries", price: 60, wait: 8 },
  { id: 62, category: "Continental", item: "Peri Peri Fries", price: 70, wait: 8 },
  { id: 63, category: "Continental", item: "Veg Sandwich", price: 60, wait: 10 },
  { id: 64, category: "Continental", item: "Paneer Sandwich", price: 70, wait: 12 },
  { id: 65, category: "Continental", item: "Cheese Sandwich", price: 70, wait: 10 },
  { id: 66, category: "Continental", item: "Paneer Cheese Sandwich", price: 80, wait: 12 },
  { id: 67, category: "Continental", item: "Veg Cheese Burger", price: 80, wait: 12 },
  { id: 68, category: "Continental", item: "Manchurian Frankee", price: 60, wait: 12 },
  { id: 69, category: "Continental", item: "Paneer Frankee", price: 60, wait: 12 },
  { id: 70, category: "Continental", item: "Palak Paneer Frankee", price: 70, wait: 12 },
  { id: 71, category: "Continental", item: "Extra Cheese", price: 20, wait: 2 },
  { id: 72, category: "Continental", item: "Veg Cheese Momos", price: 60, wait: 12 },
  { id: 73, category: "Continental", item: "Kurkure Momos", price: 70, wait: 12 },
  { id: 74, category: "Continental", item: "Paneer Momos", price: 60, wait: 12 },
  { id: 75, category: "Continental", item: "White Sauce Pasta", price: 100, wait: 15 },
  { id: 76, category: "Continental", item: "Mixed Sauce Pasta", price: 100, wait: 15 },
  { id: 77, category: "Continental", item: "Mac & Cheese Pasta", price: 100, wait: 15 },
];
